package by.htp.project.controller.command;

public enum CommandName {
	GOTOREGISTERPAGE, 
	SAVENEWUSER, 
	LOGOUT, 
	GOTONEWSREADPAGE, 
	GOTONEWSEDITPAGE,
	SAVEEDITEDNEWS, 
	GOTOSIGNINPAGE, 
	SIGNIN, 
	GOTOHOMEUSERPAGE, 
	DELETENEWS
}
